### create user
POST http://localhost:3000/users
Content-Type: application/json
Origin: http://localhost:3030

{ "user": { 
        "first_name": "Alex",
        "email": "alex@test.com",
        "password":"password",
        "password_confirmation":"password"
    }
}

### Sign in with admin
POST http://localhost:3000/users/sign_in
Content-Type: application/json
Origin: http://localhost:3030

{ 
    "user": {
            "email":"admin@admin.com",
            "password":"password"
        }
}

### Sign in with regular user details
POST http://localhost:3000/users/sign_in
Content-Type: application/json
Origin: http://localhost:3030

{ 
    "user": {
            "email":"alex@test.com",
            "password":"password"
        }
}

### Test log out
DELETE http://localhost:3000/users/sign_out
Content-Type: application/json
Authorization: Bearer 

### Index method
GET http://localhost:3000/items

### Test successfully posts an item
POST http://localhost:3000/items
Content-Type: application/json
Authorization: Bearer 

{
    "category_id": 1,
    "name" : "Created by normal",
    "price" : 3.9,
    "description": "the first pokemon"
}

### Unsuccessfully post an item (minimum name length: 3)
POST http://localhost:3000/items
Content-Type: application/json
Authorization: Bearer 

{
    "category_id": 1,
    "name" : "Kh",
    "price" : 6.9,
    "description": "the second pokemon"
}

### show item id: 1
GET http://localhost:3000/items/1

### unsuccessfully show item id 5000
GET http://localhost:3000/items/5000

### update an item
PUT http://localhost:3000/items/2
Content-Type: application/json
Authorization: Bearer 

{
    "category_id": 1,
    "name" : "Osaka",
    "price" : 6.9,
    "description": "the second biggest city"
}

### successfully delete item with id 1
DELETE http://localhost:3000/items/4
Content-Type: application/json
Authorization: Bearer 

### unsuccessfully delete item with id 1000
DELETE http://localhost:3000/items/1000



### DELETE items
DELETE http://localhost:3000/items/3
Content-Type: application/json
Authorization: Bearer 
