### create user
POST http://localhost:3000/users
Content-Type: application/json

{ "user": { 
        "first_name": "Alex",
        "email": "adam@test.com",
        "password":"password",
        "password_confirmation":"password"
    }
}

### Sign in with correct details
POST http://localhost:3000/users/sign_in
Content-Type: application/json

{ 
    "user": {
            "email":"admin@admin.com",
            "password":"password"
        }
}

### Index method
GET http://localhost:3000/items

### Test successfully posts an item
POST http://localhost:3000/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjMmIwMDgxMS1hMDU1LTQxOGEtYjMxYS1iOTI3NmQ5MmRkMTQiLCJzdWIiOiIxMCIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTYyNjQ5NDU0NywiZXhwIjoxNjI2NDk2MzQ3fQ.m9z_mjqYgg0nZ5UJaA0p1ulnIZE_ThB4ZJhfaUBT3mY

{
    "category_id": 1,
    "name" : "nobita",
    "price" : 3.9,
    "description": "the first pokemon"
}

### Unsuccessfully post an item
POST http://localhost:3000/items
Content-Type: application/json

{
    "category_id": 1,
    "name" : "Ba",
    "price" : 6.9,
    "description": "the second pokemon"
}

### show item id: 1
GET http://localhost:3000/items/1

### unsuccessfully show item id 5000
GET http://localhost:3000/items/5000

### update an item
PUT http://localhost:3000/items/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjI2Njc2Mjk1LCJleHAiOjE2MjY3NjI2OTUsImp0aSI6IjVlZjcwODlhLTVkMmQtNDA3Mi05ZmFlLWI5MTkxNzMwOWVjZCJ9.gcVmOR1GCS5LdwjisCs2l2LKLweZzCTl5bOa-rHZypc

{
    "category_id": 1,
    "name" : "Osaka",
    "price" : 6.9,
    "description": "the second biggest city"
}

### successfully delete item with id 1
DELETE http://localhost:3000/items/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjMmIwMDgxMS1hMDU1LTQxOGEtYjMxYS1iOTI3NmQ5MmRkMTQiLCJzdWIiOiIxMCIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTYyNjQ5NDU0NywiZXhwIjoxNjI2NDk2MzQ3fQ.m9z_mjqYgg0nZ5UJaA0p1ulnIZE_ThB4ZJhfaUBT3mY

### unsuccessfully delete item with id 1000
DELETE http://localhost:3000/items/1000



### Categories index method
GET http://localhost:3000/categories

### Test successfully posts an category
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjI2MjM1OTk4LCJleHAiOjE2MjYyMzk1OTgsImp0aSI6ImY2OWMyZGIyLTdlMmYtNDE1Ni1iNzA4LTZhYzFjYjk3ZTllNCJ9.ixUlx-0yk1_rv3ol5s-BQOmste-ifVYlpH8F3V01q-c
{
    "name": "drink"
}

### Unsuccessfully post an category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name" : "Ba",
}

### show category id: 1
GET http://localhost:3000/categories/1

### unsuccessfully show category id 5000
GET http://localhost:3000/categories/5000

### update a category
PUT http://localhost:3000/categories/1
Content-Type: application/json

{
    "name": "pokemon"
}

### successfully delete category with id 3
DELETE http://localhost:3000/categories/3

### unsuccessfully delete category with id 1000
DELETE http://localhost:3000/categories/3000


### create user
POST http://localhost:3000/users
Content-Type: application/json

{ "user": 
    {
        "email": "alex@test.com",
        "password":"password",
        "password_confirmation":"password"
    }
}

### Sign in with correct details
POST http://localhost:3000/users/sign_in
Content-Type: application/json

{ "user": 
    {
        "email": "alex@test.com",
        "password":"password"
    }
}

### Integration Signin
POST http://localhost:3000/users/sign_in
Content-Type: application/json
Origin: http://localhost:3030

{ 
    "user": {
            "email":"test@example.com",
            "password":"12345678"
        }
}

## Test log out
DELETE http://localhost:3000/users/sign_out
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5N2Y2MmQ5ZS0xYjA5LTQ1YWYtYmYzZi1hODg0MzZkY2U2OGIiLCJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjI2Njc0NjE1LCJleHAiOjE2MjY3NjEwMTV9.5-Gt_bKpOJjRRXpIDaX0GI03Wi78s9DHJvfPwPsMSH8
